import type {
  AgentStreamBus,
  AgentStreamEvent,
  ArtifactStore,
  GovernanceEngine,
  IterationContractRegistry,
  JournalWriter,
  ManifestProducer,
  RunnerSystem,
  StatePersistence,
} from '@ai-dev-orchestrator/ports';
import type {
  ArtifactRef,
  ArtifactType,
  DispatchResult,
  PersistedState,
  RoleId,
  RunManifest,
  TransitionDecision,
} from '@ai-dev-orchestrator/schemas';
import { vi } from 'vitest';

export function createArtifactRef(type: ArtifactType, version = 1): ArtifactRef {
  return { type, name: type, version, checksum: 'abc' };
}

export type TrackingArtifactStore = ArtifactStore & {
  stored: Map<string, { version: number; content: string }>;
};

export function createMockArtifactStore(): TrackingArtifactStore {
  const stored = new Map<string, { version: number; content: string }>();

  return {
    stored,
    store: vi.fn(
      (input: { type: ArtifactType; name: string; content: string; producedBy: string }) => {
        const existing = stored.get(input.type);
        const version = existing ? existing.version + 1 : 1;
        stored.set(input.type, { version, content: input.content });
        return Promise.resolve(createArtifactRef(input.type, version));
      },
    ),
    getLatest: vi.fn((type: ArtifactType) => {
      const entry = stored.get(type);
      if (!entry) {
        return Promise.resolve(null);
      }
      return Promise.resolve({
        ref: createArtifactRef(type, entry.version),
        type,
        name: type,
        version: entry.version,
        content: entry.content,
        checksum: 'abc',
        producedBy: 'test',
        createdAt: new Date().toISOString(),
        sizeBytes: entry.content.length,
      });
    }),
    get: vi.fn((ref: ArtifactRef) => {
      const entry = stored.get(ref.type);
      if (!entry) {
        return Promise.resolve(null as never);
      }
      return Promise.resolve({
        ref: createArtifactRef(ref.type, entry.version),
        type: ref.type,
        name: ref.type,
        version: entry.version,
        content: entry.content,
        checksum: 'abc',
        producedBy: 'test',
        createdAt: new Date().toISOString(),
        sizeBytes: entry.content.length,
      });
    }),
    list: vi.fn((query: { type?: ArtifactType }) => {
      if (query.type) {
        const entry = stored.get(query.type);
        if (!entry) {
          return Promise.resolve([]);
        }
        return Promise.resolve([createArtifactRef(query.type, entry.version)]);
      }
      return Promise.resolve([]);
    }),
    history: vi.fn(() => Promise.resolve([])),
    verify: vi.fn(() =>
      Promise.resolve({
        valid: true,
        expectedChecksum: 'abc',
        actualChecksum: 'abc',
        ref: createArtifactRef('plan'),
      }),
    ),
    inventory: vi.fn(() =>
      Promise.resolve({ runId: '', artifacts: [], totalCount: 0, totalSizeBytes: 0 }),
    ),
  };
}

const DEFAULT_ROLE_TO_ARTIFACT: Partial<Record<RoleId, ArtifactType>> = {
  requirements_analyst: 'canonical_specification',
  context_analyst: 'codebase_context',
  codebase_analyst: 'codebase_context',
  planner: 'plan',
  plan_reviewer: 'plan_review',
  implementer: 'implementation',
  test_engineer: 'test_suite',
  static_reviewer: 'static_review',
  security_reviewer: 'security_review',
  performance_reviewer: 'performance_review',
  adversarial_reviewer: 'adversarial_review',
  design_reviewer: 'design_review',
  docs_reviewer: 'docs_review',
  ux_reviewer: 'ux_review',
  report_synthesizer: 'review_report',
  remediation_triage: 'remediation_plan',
  judge: 'judge_decision',
  verifier: 'verification',
  summary_writer: 'release_summary',
  review_findings_writer: 'review_findings',
  acceptance_validator: 'acceptance_validation',
};

function defaultContentForArtifact(artifactType: string, role: string): string {
  if (artifactType.endsWith('_review')) {
    return '---\napproved: true\nfindings: []\n---\nLooks good.';
  }
  if (artifactType === 'plan') {
    return JSON.stringify({
      summary: 'Fixture plan',
      tasks: [{ taskId: 'task-1', description: 'Fixture task', files: [], dependencies: [] }],
    });
  }
  if (artifactType === 'verification') {
    return JSON.stringify({ passed: true, failures: [] });
  }
  return `Generated by ${role}`;
}

export interface MockRunnerOptions {
  artifactStore?: ArtifactStore;
  roleToArtifactType?: Record<string, ArtifactType>;
}

export function createMockRunnerSystem(options: MockRunnerOptions = {}): RunnerSystem {
  const roleMap: Record<string, ArtifactType | undefined> = {
    ...DEFAULT_ROLE_TO_ARTIFACT,
    ...options.roleToArtifactType,
  };

  async function handleDispatch(request: {
    role: string;
    runId: string;
    stateId: string;
  }): Promise<DispatchResult> {
    const artifactType = roleMap[request.role] ?? (request.role as ArtifactType);
    const ref = createArtifactRef(artifactType);
    const content = defaultContentForArtifact(artifactType, request.role);

    if (options.artifactStore) {
      await options.artifactStore.store({
        type: artifactType,
        name: artifactType,
        content,
        producedBy: request.role,
      });
    }

    return {
      workerId: `w-${request.role}`,
      status: 'success' as const,
      role: request.role as RoleId,
      outputArtifacts: [ref],
      metrics: {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationMs: 10,
        inputTokens: 100,
        outputTokens: 50,
        retryCount: 0,
        modelUsed: 'fixture-model',
      },
    };
  }

  return {
    dispatch: vi.fn(handleDispatch),
    dispatchParallel: vi.fn(
      async (requests: readonly { role: string; runId: string; stateId: string }[]) => {
        const results: DispatchResult[] = [];
        for (const request of requests) {
          results.push(await handleDispatch(request));
        }
        return results;
      },
    ),
    getWorkerStatus: vi.fn().mockReturnValue(null),
    cancelWorker: vi.fn(),
    cancelAllWorkers: vi.fn().mockResolvedValue(undefined),
    setWorkerCounter: vi.fn(),
  };
}

export function createMockStatePersistence(): StatePersistence {
  const states = new Map<string, PersistedState>();
  return {
    save: vi.fn((state: PersistedState) => {
      states.set(state.runId, state);
      return Promise.resolve();
    }),
    load: vi.fn((runId: string) => states.get(runId) ?? null),
    exists: vi.fn((runId: string) => states.has(runId)),
    validate: vi.fn(() => ({ valid: true, errors: [] as string[], warnings: [] as string[] })),
    probeLock: vi.fn(() => ({
      exists: false,
      pid: 0,
      pidRunning: false,
      hostname: '',
      unreadable: false,
    })),
    acquireLock: vi.fn(() => ({
      runId: '' as never,
      pid: process.pid,
      acquiredAt: new Date().toISOString(),
      lockPath: '',
      hostname: '',
    })),
    releaseLock: vi.fn(),
    reconstructFromJournal: vi.fn().mockReturnValue(null),
  };
}

export function createMockGovernance(): GovernanceEngine {
  return {
    evaluateTransition: vi.fn((): TransitionDecision => ({
      allowed: true,
      reason: 'approved by governance',
    })),
    checkAgreement: vi.fn(() => ({ exists: true, valid: true })),
    recordDecision: vi.fn(),
  };
}

export function createMockManifestProducer(): ManifestProducer {
  return {
    produce: vi.fn((): RunManifest => ({
      runId: '',
      version: '1.0.0',
      repository: 'test',
      workflow: { name: 'default', version: '1.0.0' },
      timing: {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        totalDurationMs: 100,
        stateTimings: [],
      },
      status: 'completed',
      finalState: 'DONE',
      activeRoles: [],
      artifactInventory: [],
      totalArtifacts: 0,
      totalArtifactSizeBytes: 0,
      iterations: [],
      governanceDecisions: 0,
      escalations: 0,
      humanInterventions: 0,
      agreements: [],
      tokenUsage: { totalInputTokens: 0, totalOutputTokens: 0, totalTokens: 0, byRole: {} },
    })),
  };
}

export function createMockContractRegistry(): IterationContractRegistry {
  return {
    getContract: vi.fn().mockReturnValue(null),
    listContracts: vi.fn().mockReturnValue([]),
    getContractForState: vi.fn().mockReturnValue(null),
    getIterationState: vi.fn(),
    recordStateEntry: vi.fn(),
    restoreIterationCounts: vi.fn(),
    restoreJudgeArbitrationCounts: vi.fn(),
    resetIterationCount: vi.fn(),
  };
}

export function createMockJournalWriter(): JournalWriter {
  return {
    append: vi.fn(),
    appendBatch: vi.fn(),
  };
}

export function createMockStreamBus(): AgentStreamBus & { events: AgentStreamEvent[] } {
  const events: AgentStreamEvent[] = [];
  return {
    events,
    publish: (event: AgentStreamEvent) => events.push(event),
    subscribe: () => '',
    unsubscribe: () => {},
    getClientCount: () => 0,
  };
}
