import { mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { DefaultIterationContractRegistry } from '@ai-dev-orchestrator/governance';
import { DefaultJournalReader, DefaultJournalWriter } from '@ai-dev-orchestrator/journal';
import type { GovernanceEngine, RunnerSystem } from '@ai-dev-orchestrator/ports';
import type {
  ArtifactType,
  DispatchResult,
  RoleId,
  TransitionDecision,
  WorkflowDefinition,
} from '@ai-dev-orchestrator/schemas';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { LifecycleController } from '@ai-dev-orchestrator/workflow';

import {
  createMockArtifactStore,
  createMockGovernance,
  createMockManifestProducer,
  createMockStatePersistence,
} from '../helpers/mock-ports';
import type { TrackingArtifactStore } from '../helpers/mock-ports';

const PR_REVIEW_ROLE_TO_ARTIFACT: Record<string, ArtifactType> = {
  setup_worker: 'intake_requirements',
  context_analyst: 'canonical_specification',
  diff_worker: 'codebase_context',
  static_reviewer: 'static_review',
  design_reviewer: 'design_review',
  security_reviewer: 'security_review',
  performance_reviewer: 'performance_review',
  adversarial_reviewer: 'adversarial_review',
  docs_reviewer: 'docs_review',
  ux_reviewer: 'ux_review',
  report_synthesizer: 'review_report',
  review_findings_writer: 'review_findings',
  publish_worker: 'release_summary',
  cleanup_worker: 'release_summary',
};

function prReviewContent(artifactType: string, role: string): string {
  if (artifactType.endsWith('_review')) {
    return '---\napproved: true\nfindings: []\n---\nLooks good.';
  }
  if (artifactType === 'review_report') {
    return JSON.stringify({ summary: 'No critical issues found', findings: [] });
  }
  if (artifactType === 'review_findings') {
    return JSON.stringify({ findings: [], summary: 'Clean PR' });
  }
  return `Generated by ${role}`;
}

function createPrReviewRunner(artifactStore: TrackingArtifactStore): RunnerSystem {
  async function handleDispatch(request: {
    role: string;
    runId: string;
    stateId: string;
  }): Promise<DispatchResult> {
    const artifactType = PR_REVIEW_ROLE_TO_ARTIFACT[request.role] ?? (request.role as ArtifactType);
    const content = prReviewContent(artifactType, request.role);

    await artifactStore.store({
      type: artifactType,
      name: artifactType,
      content,
      producedBy: request.role,
    });

    return {
      workerId: `w-${request.role}`,
      status: 'success' as const,
      role: request.role as RoleId,
      outputArtifacts: [{ type: artifactType, name: artifactType, version: 1, checksum: 'abc' }],
      metrics: {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationMs: 10,
        inputTokens: 100,
        outputTokens: 50,
        retryCount: 0,
        modelUsed: 'fixture-model',
      },
    };
  }

  return {
    dispatch: vi.fn(handleDispatch),
    dispatchParallel: vi.fn(
      async (requests: readonly { role: string; runId: string; stateId: string }[]) => {
        const results: DispatchResult[] = [];
        for (const req of requests) {
          results.push(await handleDispatch(req));
        }
        return results;
      },
    ),
    getWorkerStatus: vi.fn().mockReturnValue(null),
    cancelWorker: vi.fn(),
    cancelAllWorkers: vi.fn().mockResolvedValue(undefined),
    setWorkerCounter: vi.fn(),
  };
}

/**
 * Test workflow mirroring the pr-review YAML structure but replacing all
 * `run_script` actions with `dispatch_worker` so the mock runner can handle them.
 */
const TEST_PR_REVIEW_WORKFLOW: WorkflowDefinition = {
  name: 'pr-review',
  version: '1.0.0',
  initialState: 'SETUP',
  terminalStates: ['DONE', 'FAILED', 'ABORTED'],
  states: {
    SETUP: {
      type: 'action',
      description: 'Setup PR repository',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'setup_worker' } }],
      transitions: [
        {
          target: 'INTAKE',
          trigger: 'completion',
          guards: [],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    INTAKE: {
      type: 'action',
      description: 'Validate inputs and resolve source references',
      entryActions: [
        { type: 'record_journal', params: { event: 'run_started' } },
        { type: 'dispatch_worker', params: { role: 'context_analyst' } },
      ],
      transitions: [
        {
          target: 'DIFF_COMPUTATION',
          trigger: 'completion',
          guards: [
            { type: 'artifact_exists', params: { artifactType: 'canonical_specification' } },
          ],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    DIFF_COMPUTATION: {
      type: 'action',
      description: 'Pre-compute PR diff',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'diff_worker' } }],
      transitions: [
        {
          target: 'REVIEW_EXECUTION',
          trigger: 'completion',
          guards: [],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    REVIEW_EXECUTION: {
      type: 'review',
      description: 'Parallel multi-perspective review of the PR',
      entryActions: [
        {
          type: 'dispatch_parallel_workers',
          params: {
            roles: [
              'static_reviewer',
              'design_reviewer',
              'security_reviewer',
              'performance_reviewer',
              'adversarial_reviewer',
              'docs_reviewer',
              'ux_reviewer',
            ],
          },
        },
      ],
      transitions: [
        {
          target: 'REVIEW_SYNTHESIS',
          trigger: 'review_approved',
          guards: [],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'REVIEW_SYNTHESIS',
          trigger: 'review_rejected',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
        {
          target: 'ABORTED',
          trigger: 'iteration_exhausted',
          guards: [],
          governanceRequired: false,
          priority: 3,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 4,
        },
      ],
    },
    REVIEW_SYNTHESIS: {
      type: 'action',
      description: 'Synthesize review findings into a unified report',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'report_synthesizer' } }],
      transitions: [
        {
          target: 'WRAP_UP',
          trigger: 'completion',
          guards: [{ type: 'artifact_exists', params: { artifactType: 'review_report' } }],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
        {
          target: 'FAILED',
          trigger: 'completion',
          guards: [],
          governanceRequired: false,
          priority: 3,
        },
      ],
    },
    WRAP_UP: {
      type: 'action',
      description: 'Generate compact findings report',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'review_findings_writer' } }],
      transitions: [
        {
          target: 'PUBLISH_FINDINGS',
          trigger: 'completion',
          guards: [{ type: 'artifact_exists', params: { artifactType: 'review_findings' } }],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    PUBLISH_FINDINGS: {
      type: 'action',
      description: 'Upload review findings',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'publish_worker' } }],
      transitions: [
        {
          target: 'CLEANUP',
          trigger: 'completion',
          guards: [],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'FAILED',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    CLEANUP: {
      type: 'action',
      description: 'Remove cloned repository temp directory',
      entryActions: [{ type: 'dispatch_worker', params: { role: 'cleanup_worker' } }],
      transitions: [
        {
          target: 'DONE',
          trigger: 'completion',
          guards: [],
          governanceRequired: false,
          priority: 1,
        },
        {
          target: 'DONE',
          trigger: 'failure',
          guards: [],
          governanceRequired: false,
          priority: 2,
        },
      ],
    },
    DONE: {
      type: 'terminal',
      description: 'Review completed',
      entryActions: [
        { type: 'produce_manifest', params: {} },
        { type: 'record_journal', params: { event: 'run_completed' } },
      ],
      transitions: [],
    },
    FAILED: {
      type: 'terminal',
      description: 'Review failed',
      entryActions: [{ type: 'record_journal', params: { event: 'run_failed' } }],
      transitions: [],
    },
    ABORTED: {
      type: 'terminal',
      description: 'Review aborted',
      entryActions: [{ type: 'record_journal', params: { event: 'run_aborted' } }],
      transitions: [],
    },
  },
};

const TEST_DIR = join(tmpdir(), `pr-review-integration-${String(Date.now())}`);

let journalPath: string;

beforeEach(() => {
  mkdirSync(TEST_DIR, { recursive: true });
  journalPath = join(TEST_DIR, 'journal.md');
});

afterEach(() => {
  rmSync(TEST_DIR, { recursive: true, force: true });
});

describe('PR Review Workflow Integration', () => {
  it('happy path: SETUP → DONE produces expected artifacts', async () => {
    const artifactStore = createMockArtifactStore();
    const runner = createPrReviewRunner(artifactStore);
    const governance = createMockGovernance();
    const contractRegistry = new DefaultIterationContractRegistry();
    const journalWriter = new DefaultJournalWriter(journalPath, 'run-pr-001');
    const statePersistence = createMockStatePersistence();
    const manifestProducer = createMockManifestProducer();

    const controller = new LifecycleController({
      runner,
      artifactStore,
      governanceEngine: governance,
      contractRegistry,
      journalWriter,
      statePersistence,
      manifestProducer,
    });

    const config = {
      runId: 'run-pr-001',
      workflowDefinition: TEST_PR_REVIEW_WORKFLOW,
      governancePolicy: {},
      roleAssignments: {},
      sources: ['https://github.com/org/repo/pull/42'],
    };

    let result = await controller.start(config);

    let iterations = 0;
    while (
      result.finalState !== 'DONE' &&
      result.finalState !== 'FAILED' &&
      result.finalState !== 'ABORTED' &&
      iterations < 15
    ) {
      result = await controller.resume({ type: 'approval', content: 'Approved' });
      iterations++;
    }

    expect(result.finalState).toBe('DONE');

    expect(artifactStore.stored.has('canonical_specification')).toBe(true);
    expect(artifactStore.stored.has('review_report')).toBe(true);
    expect(artifactStore.stored.has('review_findings')).toBe(true);
    expect(artifactStore.stored.has('static_review')).toBe(true);
    expect(artifactStore.stored.has('security_review')).toBe(true);

    // eslint-disable-next-line @typescript-eslint/unbound-method
    expect(runner.dispatchParallel).toHaveBeenCalled();

    const reader = new DefaultJournalReader(journalPath);
    const events = reader.readAll();
    expect(events.some((e) => e.type === 'run_started')).toBe(true);
    expect(events.some((e) => e.type === 'run_completed')).toBe(true);

    const transitions = events.filter((e) => e.type === 'state_transition');
    const visited = new Set<string>();
    for (const t of transitions) {
      if ('from' in t.data) {
        visited.add(t.data.from);
      }
      if ('to' in t.data) {
        visited.add(t.data.to);
      }
    }
    expect(visited.has('SETUP')).toBe(true);
    expect(visited.has('INTAKE')).toBe(true);
    expect(visited.has('REVIEW_EXECUTION')).toBe(true);
    expect(visited.has('REVIEW_SYNTHESIS')).toBe(true);
    expect(visited.has('DONE')).toBe(true);
  });

  it('sources propagate through config', async () => {
    const artifactStore = createMockArtifactStore();
    const runner = createPrReviewRunner(artifactStore);
    const governance = createMockGovernance();
    const contractRegistry = new DefaultIterationContractRegistry();
    const journalWriter = new DefaultJournalWriter(journalPath, 'run-pr-sources-001');
    const statePersistence = createMockStatePersistence();
    const manifestProducer = createMockManifestProducer();

    const controller = new LifecycleController({
      runner,
      artifactStore,
      governanceEngine: governance,
      contractRegistry,
      journalWriter,
      statePersistence,
      manifestProducer,
    });

    const prUrl = 'https://github.com/org/repo/pull/42';
    const config = {
      runId: 'run-pr-sources-001',
      workflowDefinition: TEST_PR_REVIEW_WORKFLOW,
      governancePolicy: {},
      roleAssignments: {},
      sources: [prUrl],
    };

    await controller.start(config);

    const state = controller.getState();
    expect(state.runId).toBe('run-pr-sources-001');

    // eslint-disable-next-line @typescript-eslint/unbound-method
    expect(statePersistence.save).toHaveBeenCalled();
  });

  it('REVIEW_EXECUTION governance block → FAILED', async () => {
    const artifactStore = createMockArtifactStore();
    const runner = createPrReviewRunner(artifactStore);
    let callCount = 0;

    const governance: GovernanceEngine = {
      evaluateTransition: vi.fn((req: { from: string; to: string }): TransitionDecision => {
        if (req.from === req.to) {
          return { allowed: true, reason: 'pre-dispatch pass' };
        }
        callCount++;
        if (req.from === 'REVIEW_EXECUTION' && callCount <= 3) {
          return { allowed: false, reason: 'governance blocked' };
        }
        return { allowed: true, reason: 'approved' };
      }),
      checkAgreement: vi.fn(() => ({ exists: true, valid: true })),
      recordDecision: vi.fn(),
    };

    const contractRegistry = new DefaultIterationContractRegistry();
    const journalWriter = new DefaultJournalWriter(journalPath, 'run-pr-fail-001');
    const statePersistence = createMockStatePersistence();
    const manifestProducer = createMockManifestProducer();

    const controller = new LifecycleController({
      runner,
      artifactStore,
      governanceEngine: governance,
      contractRegistry,
      journalWriter,
      statePersistence,
      manifestProducer,
    });

    const config = {
      runId: 'run-pr-fail-001',
      workflowDefinition: TEST_PR_REVIEW_WORKFLOW,
      governancePolicy: {},
      roleAssignments: {},
      sources: ['https://github.com/org/repo/pull/99'],
    };

    let result = await controller.start(config);

    let iterations = 0;
    while (
      result.finalState !== 'DONE' &&
      result.finalState !== 'FAILED' &&
      result.finalState !== 'ABORTED' &&
      iterations < 15
    ) {
      result = await controller.resume({ type: 'approval', content: 'Approved' });
      iterations++;
    }

    expect(['DONE', 'FAILED', 'ABORTED']).toContain(result.finalState);
  });
});
