import { mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { DefaultIterationContractRegistry } from '@ai-orchestrator/governance';
import { DefaultJournalReader, DefaultJournalWriter } from '@ai-orchestrator/journal';
import type { RunnerSystem } from '@ai-orchestrator/ports';
import type { ArtifactType, DispatchResult, RoleId } from '@ai-orchestrator/schemas';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { LifecycleController } from '@ai-orchestrator/workflow';

import { TEST_WORKFLOW } from '../fixtures/test-defaults';
import {
  createMockArtifactStore,
  createMockGovernance,
  createMockManifestProducer,
  createMockStatePersistence,
} from '../helpers/mock-ports';
import type { TrackingArtifactStore } from '../helpers/mock-ports';

const TEST_DIR = join(tmpdir(), `scenario-tests-${String(Date.now())}`);

const DEFAULT_ROLE_TO_ARTIFACT: Partial<Record<string, ArtifactType>> = {
  requirements_analyst: 'canonical_specification',
  planner: 'plan',
  plan_reviewer: 'plan_review',
  implementer: 'implementation',
  static_reviewer: 'static_review',
  security_reviewer: 'security_review',
  performance_reviewer: 'performance_review',
  adversarial_reviewer: 'adversarial_review',
  design_reviewer: 'design_review',
  docs_reviewer: 'docs_review',
  ux_reviewer: 'ux_review',
  judge: 'judge_decision',
  verifier: 'verification',
  summary_writer: 'release_summary',
};

function defaultContent(artifactType: string, _role: string): string {
  if (artifactType.endsWith('_review')) {
    return '---\napproved: true\nfindings: []\n---\nLooks good.';
  }
  if (artifactType === 'plan') {
    return JSON.stringify({
      summary: 'Fixture plan',
      tasks: [{ taskId: 'task-1', description: 'Fixture task', files: [], dependencies: [] }],
    });
  }
  if (artifactType === 'verification') {
    return JSON.stringify({ passed: true, failures: [] });
  }
  if (artifactType === 'judge_decision') {
    return JSON.stringify({ approved: true, planLevelIssue: false });
  }
  return `Generated by ${_role}`;
}

type ContentOverride = (
  role: string,
  artifactType: string,
  callIndex: number,
) => string | undefined;

type MetricsOverride = (
  role: string,
  callIndex: number,
) => { inputTokens: number; outputTokens: number } | undefined;

function createScenarioRunner(
  artifactStore: TrackingArtifactStore,
  contentOverride?: ContentOverride,
  metricsOverride?: MetricsOverride,
): RunnerSystem {
  const callCounts: Record<string, number> = {};

  async function handleDispatch(request: {
    role: string;
    runId: string;
    stateId: string;
  }): Promise<DispatchResult> {
    callCounts[request.role] = (callCounts[request.role] ?? 0) + 1;
    const callIndex = callCounts[request.role];
    const artifactType = DEFAULT_ROLE_TO_ARTIFACT[request.role] ?? (request.role as ArtifactType);

    const customContent = contentOverride?.(request.role, artifactType, callIndex);
    const content = customContent ?? defaultContent(artifactType, request.role);

    await artifactStore.store({
      type: artifactType,
      name: artifactType,
      content,
      producedBy: request.role,
    });

    const customMetrics = metricsOverride?.(request.role, callIndex);

    return {
      workerId: `w-${request.role}-${String(callIndex)}`,
      status: 'success' as const,
      role: request.role as RoleId,
      outputArtifacts: [
        { type: artifactType, name: artifactType, version: callIndex, checksum: 'abc' },
      ],
      metrics: {
        startedAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        durationMs: 10,
        inputTokens: customMetrics?.inputTokens ?? 100,
        outputTokens: customMetrics?.outputTokens ?? 50,
        retryCount: 0,
        modelUsed: 'fixture-model',
      },
    };
  }

  return {
    dispatch: vi.fn(handleDispatch),
    dispatchParallel: vi.fn(
      async (requests: readonly { role: string; runId: string; stateId: string }[]) => {
        const results: DispatchResult[] = [];
        for (const req of requests) {
          results.push(await handleDispatch(req));
        }
        return results;
      },
    ),
    getWorkerStatus: vi.fn().mockReturnValue(null),
    cancelWorker: vi.fn(),
    cancelAllWorkers: vi.fn().mockResolvedValue(undefined),
    setWorkerCounter: vi.fn(),
  };
}

function driveToCompletion(
  controller: LifecycleController,
  maxIterations = 15,
): Promise<{ finalState: string }> {
  return (async () => {
    let result = await controller.resume({ type: 'approval', content: 'Approved' });
    let iterations = 0;
    while (
      result.finalState !== 'DONE' &&
      result.finalState !== 'FAILED' &&
      result.finalState !== 'ABORTED' &&
      iterations < maxIterations
    ) {
      result = await controller.resume({ type: 'approval', content: 'Approved' });
      iterations++;
    }
    return result;
  })();
}

let journalPath: string;

beforeEach(() => {
  mkdirSync(TEST_DIR, { recursive: true });
  journalPath = join(TEST_DIR, 'journal.md');
});

afterEach(() => {
  rmSync(TEST_DIR, { recursive: true, force: true });
});

describe('State Transition Scenarios', () => {
  describe('plan review rejection cycle', () => {
    it('rejects plan once then approves on re-review, completing the full workflow', async () => {
      const artifactStore = createMockArtifactStore();
      const runner = createScenarioRunner(artifactStore, (role, artifactType, callIndex) => {
        if (role === 'plan_reviewer' && callIndex === 1) {
          return '---\napproved: false\nfindings:\n  - severity: high\n    description: Plan lacks detail\n---\nRejected.';
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-plan-reject-001');
      const statePersistence = createMockStatePersistence();

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence,
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-plan-reject-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Build a notification system'],
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      const finalResult = await driveToCompletion(controller);
      expect(finalResult.finalState).toBe('DONE');

      const reader = new DefaultJournalReader(journalPath);
      const events = reader.readAll();
      const transitions = events.filter((e) => e.type === 'state_transition');
      const visitedStates = transitions.flatMap((t) => {
        const states: string[] = [];
        if ('from' in t.data) {
          states.push(t.data.from);
        }
        if ('to' in t.data) {
          states.push(t.data.to);
        }
        return states;
      });

      // Planner was dispatched twice (once rejected, once approved)
      const plannerDispatches = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
        (c: unknown[]) => (c[0] as { role: string }).role === 'planner',
      );
      expect(plannerDispatches.length).toBe(2);

      // PLANNING was visited at least twice
      expect(visitedStates.filter((s) => s === 'PLANNING').length).toBeGreaterThanOrEqual(2);
    });
  });

  describe('code review rejection → reimplementation cycle', () => {
    it('rejects code review once then approves, completing through verification', async () => {
      const artifactStore = createMockArtifactStore();

      const reviewRoles = new Set([
        'static_reviewer',
        'design_reviewer',
        'security_reviewer',
        'performance_reviewer',
        'adversarial_reviewer',
        'docs_reviewer',
        'ux_reviewer',
      ]);
      const reviewCallCounts: Record<string, number> = {};

      const runner = createScenarioRunner(artifactStore, (role, _artifactType, _callIndex) => {
        if (reviewRoles.has(role)) {
          reviewCallCounts[role] = (reviewCallCounts[role] ?? 0) + 1;
          if (reviewCallCounts[role] === 1) {
            return '---\napproved: false\nfindings:\n  - severity: high\n    description: Code quality issue\n---\nNeeds improvement.';
          }
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-code-reject-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-code-reject-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Implement user auth'],
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      const finalResult = await driveToCompletion(controller);
      expect(finalResult.finalState).toBe('DONE');

      // Implementer was dispatched at least twice
      const implDispatches = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
        (c: unknown[]) => (c[0] as { role: string }).role === 'implementer',
      );
      expect(implDispatches.length).toBeGreaterThanOrEqual(2);

      // Verification was reached
      expect(artifactStore.stored.has('verification')).toBe(true);
    });
  });

  describe('iteration exhaustion → judge review', () => {
    it('exhausts code review iterations and escalates to judge', async () => {
      const artifactStore = createMockArtifactStore();

      const reviewRoles = new Set([
        'static_reviewer',
        'design_reviewer',
        'security_reviewer',
        'performance_reviewer',
        'adversarial_reviewer',
        'docs_reviewer',
        'ux_reviewer',
      ]);

      const runner = createScenarioRunner(artifactStore, (role, _artifactType, _callIndex) => {
        if (reviewRoles.has(role)) {
          return '---\napproved: false\nfindings:\n  - severity: high\n    description: Persistent issue\n---\nNeeds work.';
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-exhaust-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-exhaust-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Implement complex feature'],
        globalTransitionLimit: 100,
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      const finalResult = await driveToCompletion(controller, 20);
      expect(finalResult.finalState).toBe('DONE');

      // Judge was dispatched (reached via iteration_exhausted)
      const judgeDispatches = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
        (c: unknown[]) => (c[0] as { role: string }).role === 'judge',
      );
      expect(judgeDispatches.length).toBeGreaterThanOrEqual(1);

      expect(artifactStore.stored.has('judge_decision')).toBe(true);
    });
  });

  describe('verification failure → reimplementation cycle', () => {
    it('fails verification with fixable failures then succeeds on retry', async () => {
      const artifactStore = createMockArtifactStore();

      const runner = createScenarioRunner(artifactStore, (role, _artifactType, callIndex) => {
        if (role === 'verifier' && callIndex === 1) {
          return JSON.stringify({
            passed: false,
            failures: [{ fixable: true, description: 'Unit test assertion failure' }],
          });
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-verify-fail-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-verify-fail-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Add notification system'],
        globalTransitionLimit: 100,
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      const finalResult = await driveToCompletion(controller, 20);
      expect(finalResult.finalState).toBe('DONE');

      // Verifier was dispatched at least twice
      const verifierDispatches = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
        (c: unknown[]) => (c[0] as { role: string }).role === 'verifier',
      );
      expect(verifierDispatches.length).toBeGreaterThanOrEqual(2);

      // Final verification artifact should show passed
      const verificationEntry = artifactStore.stored.get('verification');
      expect(verificationEntry).toBeDefined();
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- guarded by assertion above
      const parsed = JSON.parse(verificationEntry!.content) as { passed: boolean };
      expect(parsed.passed).toBe(true);
    });
  });

  describe('abort during resume', () => {
    it('abort fires during resume processing and produces ABORTED state', async () => {
      const artifactStore = createMockArtifactStore();

      let resolveDispatch!: (value: DispatchResult) => void;
      let dispatchCallCount = 0;

      const slowRunner: RunnerSystem = {
        dispatch: vi.fn().mockImplementation((request: { role: string }) => {
          dispatchCallCount++;
          if (dispatchCallCount <= 4) {
            const artifactType =
              DEFAULT_ROLE_TO_ARTIFACT[request.role] ?? (request.role as ArtifactType);
            const content = defaultContent(artifactType, request.role);
            void artifactStore.store({
              type: artifactType,
              name: artifactType,
              content,
              producedBy: request.role,
            });
            return Promise.resolve({
              workerId: `w-${String(dispatchCallCount)}`,
              status: 'success' as const,
              role: request.role as RoleId,
              outputArtifacts: [
                { type: artifactType, name: artifactType, version: 1, checksum: 'abc' },
              ],
              metrics: {
                startedAt: '',
                completedAt: '',
                durationMs: 0,
                inputTokens: 0,
                outputTokens: 0,
                retryCount: 0,
                modelUsed: '',
              },
            });
          }
          // On the 5th dispatch (after resume), hang indefinitely until resolved
          return new Promise<DispatchResult>((resolve) => {
            resolveDispatch = resolve;
          });
        }),
        dispatchParallel: vi.fn().mockResolvedValue([]),
        getWorkerStatus: vi.fn().mockReturnValue(null),
        cancelWorker: vi.fn(),
        cancelAllWorkers: vi.fn().mockResolvedValue(undefined),
        setWorkerCounter: vi.fn(),
      };

      const controller = new LifecycleController({
        runner: slowRunner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry: new DefaultIterationContractRegistry(),
        journalWriter: new DefaultJournalWriter(journalPath, 'run-abort-resume-001'),
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-abort-resume-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Build something'],
        globalTransitionLimit: 50,
      };

      const startResult = await controller.start(config);
      expect(startResult.finalState).toBe('WAITING_FOR_HUMAN');

      const resumePromise = controller.resume({ type: 'approval', content: 'Approved' });

      // Give the resume a tick to start the dispatch
      await new Promise((resolve) => {
        setTimeout(resolve, 10);
      });

      await controller.abort('User cancelled during resume');
      expect(controller.getState().currentState).toBe('ABORTED');

      // Resolve the hanging dispatch so the promise settles
      resolveDispatch({
        workerId: 'w-late',
        status: 'failure' as const,
        role: 'planner' satisfies RoleId,
        outputArtifacts: [],
        metrics: {
          startedAt: '',
          completedAt: '',
          durationMs: 0,
          inputTokens: 0,
          outputTokens: 0,
          retryCount: 0,
          modelUsed: '',
        },
      });

      const resumeResult = await resumePromise;
      expect(resumeResult.finalState).toBe('ABORTED');
    });
  });

  describe('state re-entry counting', () => {
    it('visitCount increments correctly through multiple plan review cycles', async () => {
      const artifactStore = createMockArtifactStore();

      let planReviewCount = 0;
      const runner = createScenarioRunner(artifactStore, (role, _artifactType, _callIndex) => {
        if (role === 'plan_reviewer') {
          planReviewCount++;
          if (planReviewCount <= 2) {
            return '---\napproved: false\nfindings:\n  - severity: high\n    description: Iteration issue\n---\nRejected.';
          }
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-reentry-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-reentry-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Add feature'],
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      const finalResult = await driveToCompletion(controller);
      expect(finalResult.finalState).toBe('DONE');

      const reader = new DefaultJournalReader(journalPath);
      const events = reader.readAll();
      const transitions = events.filter((e) => e.type === 'state_transition');

      // Count how many times PLANNING was entered
      const planningEntries = transitions.filter((t) => 'to' in t.data && t.data.to === 'PLANNING');
      // 2 rejections means 3 total PLANNING entries (initial + 2 returns from rejection)
      expect(planningEntries.length).toBeGreaterThanOrEqual(3);

      // Count PLAN_REVIEW entries
      const planReviewEntries = transitions.filter(
        (t) => 'to' in t.data && t.data.to === 'PLAN_REVIEW',
      );
      expect(planReviewEntries.length).toBeGreaterThanOrEqual(3);

      // Planner dispatched 3 times
      const plannerDispatches = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
        (c: unknown[]) => (c[0] as { role: string }).role === 'planner',
      );
      expect(plannerDispatches.length).toBe(3);
    });
  });

  describe('human rejection from plan review wait', () => {
    it('human_rejected from PLAN_REVIEW wait sends workflow back to REFINEMENT', async () => {
      const artifactStore = createMockArtifactStore();
      const runner = createScenarioRunner(artifactStore);

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-human-reject-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-human-reject-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Build user profiles'],
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      // Drive through the initial wait states (REFINEMENT wait) with approvals
      // until we reach PLAN_REVIEW's governance gate
      let result = await controller.resume({ type: 'approval', content: 'Approved' });
      let iterations = 0;
      while (
        result.finalState === 'WAITING_FOR_HUMAN' &&
        controller.getState().waitingContext?.requestingState !== 'PLAN_REVIEW' &&
        iterations < 10
      ) {
        result = await controller.resume({ type: 'approval', content: 'Approved' });
        iterations++;
      }

      if (
        result.finalState === 'WAITING_FOR_HUMAN' &&
        controller.getState().waitingContext?.requestingState === 'PLAN_REVIEW'
      ) {
        // Now reject from the PLAN_REVIEW wait — should go to REFINEMENT
        result = await controller.resume({
          type: 'rejection',
          content: 'The plan does not meet requirements',
        });

        // After rejection, workflow should either pause again or continue
        // The human_rejected + requestingState=PLAN_REVIEW → REFINEMENT transition
        const reader = new DefaultJournalReader(journalPath);
        const events = reader.readAll();
        const transitions = events.filter((e) => e.type === 'state_transition');
        const rejectionTransition = transitions.find(
          (t) =>
            'from' in t.data &&
            t.data.from === 'WAITING_FOR_HUMAN' &&
            'trigger' in t.data &&
            t.data.trigger === 'human_rejected',
        );
        expect(rejectionTransition).toBeDefined();

        // The target should be REFINEMENT (per the workflow definition)
        const rejectionData = rejectionTransition?.data as { to?: string } | undefined;
        expect(rejectionData?.to).toBe('REFINEMENT');
      }

      // Regardless of the path taken, drive to completion
      if (result.finalState === 'WAITING_FOR_HUMAN') {
        result = await driveToCompletion(controller);
      }
      expect(result.finalState).toBe('DONE');
    });
  });

  describe('verification escalation to human', () => {
    it('unfixable verification failure escalates to WAITING_FOR_HUMAN', async () => {
      const artifactStore = createMockArtifactStore();

      const runner = createScenarioRunner(artifactStore, (role, _artifactType, callIndex) => {
        if (role === 'verifier' && callIndex === 1) {
          return JSON.stringify({
            passed: false,
            failures: [{ fixable: false, description: 'Infrastructure dependency missing' }],
          });
        }
        return undefined;
      });

      const contractRegistry = new DefaultIterationContractRegistry();
      const journalWriter = new DefaultJournalWriter(journalPath, 'run-verify-escalate-001');

      const controller = new LifecycleController({
        runner,
        artifactStore,
        governanceEngine: createMockGovernance(),
        contractRegistry,
        journalWriter,
        statePersistence: createMockStatePersistence(),
        manifestProducer: createMockManifestProducer(),
      });

      const config = {
        runId: 'run-verify-escalate-001',
        workflowDefinition: TEST_WORKFLOW,
        governancePolicy: {},
        roleAssignments: {},
        sources: ['Deploy service'],
        globalTransitionLimit: 100,
      };

      const initial = await controller.start(config);
      expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

      // Drive through until verification fails
      let result = await controller.resume({ type: 'approval', content: 'Approved' });
      let iterations = 0;
      while (
        result.finalState !== 'DONE' &&
        result.finalState !== 'FAILED' &&
        result.finalState !== 'ABORTED' &&
        iterations < 20
      ) {
        const state = controller.getState();
        if (
          state.currentState === 'WAITING_FOR_HUMAN' &&
          state.waitingContext?.requestingState === 'VERIFICATION'
        ) {
          // Approve the escalation to continue via WRAP_UP
          result = await controller.resume({ type: 'approval', content: 'Approved anyway' });
        } else {
          result = await controller.resume({ type: 'approval', content: 'Approved' });
        }
        iterations++;
      }

      expect(result.finalState).toBe('DONE');

      const reader = new DefaultJournalReader(journalPath);
      const events = reader.readAll();
      const transitions = events.filter((e) => e.type === 'state_transition');

      // Verify that VERIFICATION → WAITING_FOR_HUMAN occurred
      const verificationEscalation = transitions.some(
        (t) =>
          'from' in t.data &&
          t.data.from === 'VERIFICATION' &&
          'to' in t.data &&
          t.data.to === 'WAITING_FOR_HUMAN',
      );
      expect(verificationEscalation).toBe(true);
    });
  });

  describe('budget limit scenarios', () => {
    describe('budget exhaustion mid-workflow → single approval drives to completion', () => {
      it('completes via DONE after a single budget escalation approval', async () => {
        const artifactStore = createMockArtifactStore();
        const runner = createScenarioRunner(artifactStore);

        const journalWriter = new DefaultJournalWriter(journalPath, 'run-budget-complete-001');

        const controller = new LifecycleController({
          runner,
          artifactStore,
          governanceEngine: createMockGovernance(),
          contractRegistry: new DefaultIterationContractRegistry(),
          journalWriter,
          statePersistence: createMockStatePersistence(),
          manifestProducer: createMockManifestProducer(),
        });

        const config = {
          runId: 'run-budget-complete-001',
          workflowDefinition: TEST_WORKFLOW,
          governancePolicy: {},
          roleAssignments: {},
          sources: ['Build a notification system'],
          budgetMaxTokens: 400,
          globalTransitionLimit: 100,
        };

        // Budget = 400 tokens. Each dispatch uses 150 tokens (100 in + 50 out).
        // After 3 dispatches (INTAKE, REFINEMENT, PLANNING) = 450 tokens → exceeds budget.
        const initial = await controller.start(config);
        expect(initial.finalState).toBe('WAITING_FOR_HUMAN');

        const state = controller.getState();
        expect(state.waitingContext?.reason).toBe('token_budget_exceeded');
        expect(state.waitingContext?.budgetExhaustion).toBeDefined();
        expect(state.waitingContext?.budgetExhaustion?.limitType).toBe('token');
        expect(state.waitingContext?.budgetExhaustion?.limit).toBe(400);
        expect(state.waitingContext?.budgetExhaustion?.current).toBeGreaterThan(400);

        // A single budget approval lets the workflow continue without further
        // budget prompts — the approval is persistent for the rest of the run.
        // driveToCompletion handles remaining regular (non-budget) WAITING_FOR_HUMAN states.
        const finalResult = await driveToCompletion(controller, 20);
        expect(finalResult.finalState).toBe('DONE');

        const reader = new DefaultJournalReader(journalPath);
        const events = reader.readAll();
        const budgetEvents = events.filter(
          (e) =>
            e.type === 'human_input_requested' &&
            'reason' in e.data &&
            e.data.reason === 'token_budget_exceeded',
        );
        expect(budgetEvents.length).toBe(1);
      });
    });

    describe('budget exhaustion → abort', () => {
      it('aborts workflow when human rejects budget escalation', async () => {
        const artifactStore = createMockArtifactStore();
        const runner = createScenarioRunner(artifactStore);

        const journalWriter = new DefaultJournalWriter(journalPath, 'run-budget-abort-001');

        const controller = new LifecycleController({
          runner,
          artifactStore,
          governanceEngine: createMockGovernance(),
          contractRegistry: new DefaultIterationContractRegistry(),
          journalWriter,
          statePersistence: createMockStatePersistence(),
          manifestProducer: createMockManifestProducer(),
        });

        const config = {
          runId: 'run-budget-abort-001',
          workflowDefinition: TEST_WORKFLOW,
          governancePolicy: {},
          roleAssignments: {},
          sources: ['Build a feature'],
          budgetMaxTokens: 400,
          globalTransitionLimit: 100,
        };

        const initial = await controller.start(config);
        expect(initial.finalState).toBe('WAITING_FOR_HUMAN');
        expect(controller.getState().waitingContext?.reason).toBe('token_budget_exceeded');

        await controller.abort('Budget too high');
        expect(controller.getState().currentState).toBe('ABORTED');

        const reader = new DefaultJournalReader(journalPath);
        const events = reader.readAll();

        const budgetEvent = events.find(
          (e) =>
            e.type === 'human_input_requested' &&
            'reason' in e.data &&
            e.data.reason === 'token_budget_exceeded',
        );
        expect(budgetEvent).toBeDefined();

        const abortEvent = events.find((e) => e.type === 'run_aborted');
        expect(abortEvent).toBeDefined();
      });
    });

    describe('post-action budget exhaustion preserves action results', () => {
      it('does not re-dispatch worker when resuming after post-action budget exceeded', async () => {
        const artifactStore = createMockArtifactStore();

        // Implementer uses high tokens to trigger post-action budget check,
        // while all other roles stay within budget on their own.
        const runner = createScenarioRunner(artifactStore, undefined, (role) => {
          if (role === 'implementer') {
            return { inputTokens: 2000, outputTokens: 2000 };
          }
          return undefined;
        });

        const journalWriter = new DefaultJournalWriter(journalPath, 'run-budget-no-redispatch-001');

        const controller = new LifecycleController({
          runner,
          artifactStore,
          governanceEngine: createMockGovernance(),
          contractRegistry: new DefaultIterationContractRegistry(),
          journalWriter,
          statePersistence: createMockStatePersistence(),
          manifestProducer: createMockManifestProducer(),
        });

        const config = {
          runId: 'run-budget-no-redispatch-001',
          workflowDefinition: TEST_WORKFLOW,
          governancePolicy: {},
          roleAssignments: {},
          sources: ['Build a feature'],
          budgetMaxTokens: 2000,
          globalTransitionLimit: 100,
        };

        // Drive through until budget is exceeded by the implementer dispatch.
        // INTAKE(150) → REFINEMENT(300) → PLANNING(450) → PLAN_REVIEW(600)
        // → WAITING_FOR_HUMAN (governance gate) → approval → IMPLEMENTATION
        // → implementer dispatch (4000 tokens) → post-action: 4600 > 2000 → budget exceeded
        let result = await controller.start(config);
        let iterations = 0;
        while (
          result.finalState === 'WAITING_FOR_HUMAN' &&
          controller.getState().waitingContext?.reason !== 'token_budget_exceeded' &&
          iterations < 10
        ) {
          result = await controller.resume({ type: 'approval', content: 'Approved' });
          iterations++;
        }

        expect(controller.getState().waitingContext?.reason).toBe('token_budget_exceeded');
        expect(controller.getState().waitingContext?.requestingState).toBe('IMPLEMENTATION');

        const implDispatchesBefore = (
          runner.dispatch as ReturnType<typeof vi.fn>
        ).mock.calls.filter(
          (c: unknown[]) => (c[0] as { role: string }).role === 'implementer',
        ).length;
        expect(implDispatchesBefore).toBe(1);

        // Approve the budget escalation — saved action results should be replayed,
        // no new dispatch of implementer.
        await controller.resume({ type: 'approval', content: 'Continue' });

        const implDispatchesAfter = (runner.dispatch as ReturnType<typeof vi.fn>).mock.calls.filter(
          (c: unknown[]) => (c[0] as { role: string }).role === 'implementer',
        ).length;
        expect(implDispatchesAfter).toBe(1);

        // Implementation artifact should exist from the saved results
        expect(artifactStore.stored.has('implementation')).toBe(true);
      });
    });
  });
});
