import { DefaultIterationContractRegistry } from '@ai-orchestrator/governance';
import type { ArtifactStore, RunnerSystem } from '@ai-orchestrator/ports';
import type {
  ArtifactType,
  DispatchResult,
  RoleId,
  WorkflowDefinition,
} from '@ai-orchestrator/schemas';
import * as fc from 'fast-check';
import { describe, expect, it, vi } from 'vitest';

import { TEST_WORKFLOW } from '../../../../test/fixtures/test-defaults';
import { LifecycleController } from '../lifecycle-controller';

const TERMINAL_STATES = new Set(TEST_WORKFLOW.terminalStates);
const ALL_STATES = Object.keys(TEST_WORKFLOW.states);
const NON_TERMINAL_STATES = ALL_STATES.filter((s) => !TERMINAL_STATES.has(s));

const DEFAULT_ROLE_TO_ARTIFACT: Partial<Record<string, ArtifactType>> = {
  requirements_analyst: 'canonical_specification',
  planner: 'plan',
  plan_reviewer: 'plan_review',
  implementer: 'implementation',
  static_reviewer: 'static_review',
  security_reviewer: 'security_review',
  performance_reviewer: 'performance_review',
  adversarial_reviewer: 'adversarial_review',
  design_reviewer: 'design_review',
  docs_reviewer: 'docs_review',
  ux_reviewer: 'ux_review',
  judge: 'judge_decision',
  verifier: 'verification',
  summary_writer: 'release_summary',
};

function approvedContent(): string {
  return '---\napproved: true\nfindings: []\n---\nApproved.';
}

function rejectedContent(): string {
  return '---\napproved: false\nfindings:\n  - severity: high\n    description: Needs work\n---\nRejected.';
}

function planContent(): string {
  return JSON.stringify({
    summary: 'Test plan',
    tasks: [{ taskId: 'task-1', description: 'Test task', files: [], dependencies: [] }],
  });
}

function verificationContent(pass: boolean): string {
  if (pass) {
    return JSON.stringify({ passed: true, failures: [] });
  }
  return JSON.stringify({
    passed: false,
    failures: [{ fixable: true, description: 'Test failure' }],
  });
}

function judgeContent(approve: boolean): string {
  return JSON.stringify({ approved: approve, planLevelIssue: false });
}

interface ReviewDecisions {
  planReviewApprovals: boolean[];
  codeReviewApprovals: boolean[];
  judgeApprovals: boolean[];
  verificationPasses: boolean[];
}

function createDecisionRunner(
  stored: Map<string, { version: number; content: string }>,
  decisions: ReviewDecisions,
): RunnerSystem {
  const counters: Record<string, number> = {};

  function contentFor(role: string, artifactType: string): string {
    counters[role] = (counters[role] ?? 0) + 1;
    const idx = counters[role] - 1;

    if (role === 'plan_reviewer') {
      const approve = decisions.planReviewApprovals[idx] ?? true;
      return approve ? approvedContent() : rejectedContent();
    }
    if (role === 'judge') {
      const approve = decisions.judgeApprovals[idx] ?? true;
      return judgeContent(approve);
    }
    if (role === 'verifier') {
      const pass = decisions.verificationPasses[idx] ?? true;
      return verificationContent(pass);
    }
    if (artifactType.endsWith('_review')) {
      const approve = decisions.codeReviewApprovals[idx] ?? true;
      return approve ? approvedContent() : rejectedContent();
    }
    if (artifactType === 'plan') {
      return planContent();
    }
    return `Generated by ${role}`;
  }

  function handleDispatch(request: {
    role: string;
    runId: string;
    stateId: string;
  }): Promise<DispatchResult> {
    const artifactType = DEFAULT_ROLE_TO_ARTIFACT[request.role] ?? (request.role as ArtifactType);
    const content = contentFor(request.role, artifactType);

    const existing = stored.get(artifactType);
    const version = existing ? existing.version + 1 : 1;
    stored.set(artifactType, { version, content });

    return Promise.resolve({
      workerId: `w-${request.role}`,
      status: 'success' as const,
      role: request.role as RoleId,
      outputArtifacts: [{ type: artifactType, name: artifactType, version, checksum: 'abc' }],
      metrics: {
        startedAt: '',
        completedAt: '',
        durationMs: 10,
        inputTokens: 100,
        outputTokens: 50,
        retryCount: 0,
        modelUsed: 'fixture-model',
      },
    });
  }

  return {
    dispatch: vi.fn(handleDispatch),
    dispatchParallel: vi.fn(
      async (requests: readonly { role: string; runId: string; stateId: string }[]) => {
        const results: DispatchResult[] = [];
        for (const req of requests) {
          results.push(await handleDispatch(req));
        }
        return results;
      },
    ),
    getWorkerStatus: vi.fn().mockReturnValue(null),
    cancelWorker: vi.fn(),
    cancelAllWorkers: vi.fn().mockResolvedValue(undefined),
    setWorkerCounter: vi.fn(),
  };
}

function createDecisionStore(
  stored: Map<string, { version: number; content: string }>,
): ArtifactStore {
  function refFor(type: string, version: number) {
    return { type: type as ArtifactType, name: type, version, checksum: 'abc' };
  }

  return {
    store: vi.fn(
      (input: { type: ArtifactType; name: string; content: string; producedBy: string }) => {
        const existing = stored.get(input.type);
        const version = existing ? existing.version + 1 : 1;
        stored.set(input.type, { version, content: input.content });
        return Promise.resolve(refFor(input.type, version));
      },
    ),
    getLatest: vi.fn((type: ArtifactType) => {
      const entry = stored.get(type);
      if (!entry) {
        return Promise.resolve(null);
      }
      return Promise.resolve({
        ref: refFor(type, entry.version),
        type,
        name: type,
        version: entry.version,
        content: entry.content,
        checksum: 'abc',
        producedBy: 'test',
        createdAt: new Date().toISOString(),
        sizeBytes: entry.content.length,
      });
    }),
    get: vi.fn((ref: { type: ArtifactType }) => {
      const entry = stored.get(ref.type);
      if (!entry) {
        return Promise.resolve(null as never);
      }
      return Promise.resolve({
        ref: refFor(ref.type, entry.version),
        type: ref.type,
        name: ref.type,
        version: entry.version,
        content: entry.content,
        checksum: 'abc',
        producedBy: 'test',
        createdAt: new Date().toISOString(),
        sizeBytes: entry.content.length,
      });
    }),
    list: vi.fn((query: { type?: ArtifactType }) => {
      if (query.type) {
        const entry = stored.get(query.type);
        if (!entry) {
          return Promise.resolve([]);
        }
        return Promise.resolve([refFor(query.type, entry.version)]);
      }
      return Promise.resolve([]);
    }),
    history: vi.fn(() => Promise.resolve([])),
    verify: vi.fn(() =>
      Promise.resolve({
        valid: true,
        expectedChecksum: 'abc',
        actualChecksum: 'abc',
        ref: refFor('plan', 1),
      }),
    ),
    inventory: vi.fn(() =>
      Promise.resolve({ runId: '', artifacts: [], totalCount: 0, totalSizeBytes: 0 }),
    ),
  };
}

function makeGovernance() {
  return {
    evaluateTransition: vi.fn(() => ({ allowed: true, reason: 'approved' })),
    checkAgreement: vi.fn(() => ({ exists: true, valid: true })),
    recordDecision: vi.fn(),
  };
}

function makePersistence() {
  const states = new Map<string, unknown>();
  return {
    save: vi.fn((state: { runId: string }) => {
      states.set(state.runId, state);
      return Promise.resolve();
    }),
    load: vi.fn((runId: string) => states.get(runId) ?? null),
    exists: vi.fn((runId: string) => states.has(runId)),
    validate: vi.fn(() => ({ valid: true, errors: [] as string[], warnings: [] as string[] })),
    probeLock: vi.fn(() => ({
      exists: false,
      pid: 0,
      pidRunning: false,
      hostname: '',
      unreadable: false,
    })),
    acquireLock: vi.fn(() => ({
      runId: '' as never,
      pid: process.pid,
      acquiredAt: '',
      lockPath: '',
      hostname: '',
    })),
    releaseLock: vi.fn(),
    reconstructFromJournal: vi.fn().mockReturnValue(null),
  };
}

function makeManifest() {
  return {
    produce: vi.fn(() => ({
      runId: '',
      version: '1.0.0',
      repository: '',
      workflow: { name: 'dev', version: '1.0.0' },
      timing: { startedAt: '', completedAt: '', totalDurationMs: 0, stateTimings: [] },
      status: 'completed',
      finalState: 'DONE',
      activeRoles: [],
      artifactInventory: [],
      totalArtifacts: 0,
      totalArtifactSizeBytes: 0,
      iterations: [],
      governanceDecisions: 0,
      escalations: 0,
      humanInterventions: 0,
      agreements: [],
      tokenUsage: { totalInputTokens: 0, totalOutputTokens: 0, totalTokens: 0, byRole: {} },
    })),
  };
}

async function runWithDecisions(decisions: ReviewDecisions): Promise<{
  finalState: string;
  stateHistory: string[];
  transitionCount: number;
}> {
  const stored = new Map<string, { version: number; content: string }>();
  const artifactStore = createDecisionStore(stored);
  const runner = createDecisionRunner(stored, decisions);
  const contractRegistry = new DefaultIterationContractRegistry();

  const controller = new LifecycleController({
    runner,
    artifactStore,
    governanceEngine: makeGovernance(),
    contractRegistry,
    journalWriter: { append: vi.fn(), appendBatch: vi.fn() },
    statePersistence: makePersistence(),
    manifestProducer: makeManifest(),
  });

  const config = {
    runId: 'run-prop-test',
    workflowDefinition: TEST_WORKFLOW,
    governancePolicy: {},
    roleAssignments: {},
    sources: ['Property test input'],
    globalTransitionLimit: 200,
  };

  let result = await controller.start(config);
  let iterations = 0;
  while (
    result.finalState !== 'DONE' &&
    result.finalState !== 'FAILED' &&
    result.finalState !== 'ABORTED' &&
    iterations < 50
  ) {
    result = await controller.resume({ type: 'approval', content: 'Approved' });
    iterations++;
  }

  const state = controller.getState();
  return {
    finalState: result.finalState,
    stateHistory: [], // state history isn't directly accessible, but we verify via finalState
    transitionCount: state.transitionCount,
  };
}

const reviewDecisionArb: fc.Arbitrary<ReviewDecisions> = fc.record({
  planReviewApprovals: fc.array(fc.boolean(), { minLength: 1, maxLength: 6 }),
  codeReviewApprovals: fc.array(fc.boolean(), { minLength: 1, maxLength: 6 }),
  judgeApprovals: fc.array(fc.boolean(), { minLength: 1, maxLength: 3 }),
  verificationPasses: fc.array(fc.boolean(), { minLength: 1, maxLength: 4 }),
});

describe('Workflow random-walk property tests', () => {
  it('every decision sequence terminates in a terminal state', async () => {
    await fc.assert(
      fc.asyncProperty(reviewDecisionArb, async (decisions) => {
        const result = await runWithDecisions(decisions);
        expect(TERMINAL_STATES.has(result.finalState)).toBe(true);
      }),
      { numRuns: 30 },
    );
  });

  it('transition count is always positive (at least one transition occurs)', async () => {
    await fc.assert(
      fc.asyncProperty(reviewDecisionArb, async (decisions) => {
        const result = await runWithDecisions(decisions);
        expect(result.transitionCount).toBeGreaterThan(0);
      }),
      { numRuns: 30 },
    );
  });

  it('all-approved decisions always reach DONE', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          planReviewApprovals: fc.constant([true]),
          codeReviewApprovals: fc.constant([true]),
          judgeApprovals: fc.constant([true]),
          verificationPasses: fc.constant([true]),
        }),
        async (decisions) => {
          const result = await runWithDecisions(decisions);
          expect(result.finalState).toBe('DONE');
        },
      ),
      { numRuns: 10 },
    );
  });

  it('rejection followed by approval reaches DONE', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          planReviewApprovals: fc.constantFrom([false, true], [false, false, true]),
          codeReviewApprovals: fc.constant([true]),
          judgeApprovals: fc.constant([true]),
          verificationPasses: fc.constant([true]),
        }),
        async (decisions) => {
          const result = await runWithDecisions(decisions);
          expect(result.finalState).toBe('DONE');
        },
      ),
      { numRuns: 10 },
    );
  });

  it('verification failure followed by success reaches DONE', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          planReviewApprovals: fc.constant([true]),
          codeReviewApprovals: fc.constant([true]),
          judgeApprovals: fc.constant([true]),
          verificationPasses: fc.constantFrom([false, true], [false, false, true]),
        }),
        async (decisions) => {
          const result = await runWithDecisions(decisions);
          expect(result.finalState).toBe('DONE');
        },
      ),
      { numRuns: 10 },
    );
  });

  it('random decisions with at least one approval path eventually terminate', async () => {
    const terminatingDecisions = fc.record({
      planReviewApprovals: fc
        .array(fc.boolean(), { minLength: 0, maxLength: 4 })
        .map((arr) => [...arr, true]),
      codeReviewApprovals: fc
        .array(fc.boolean(), { minLength: 0, maxLength: 4 })
        .map((arr) => [...arr, true]),
      judgeApprovals: fc
        .array(fc.boolean(), { minLength: 0, maxLength: 2 })
        .map((arr) => [...arr, true]),
      verificationPasses: fc
        .array(fc.boolean(), { minLength: 0, maxLength: 3 })
        .map((arr) => [...arr, true]),
    });

    await fc.assert(
      fc.asyncProperty(terminatingDecisions, async (decisions) => {
        const result = await runWithDecisions(decisions);
        expect(result.finalState).toBe('DONE');
      }),
      { numRuns: 30 },
    );
  });
});

describe('Workflow structural graph walk', () => {
  function collectReachableStates(definition: WorkflowDefinition, start: string): Set<string> {
    const visited = new Set<string>();
    const queue = [start];
    while (queue.length > 0) {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- queue.length > 0 guarantees pop() returns
      const current = queue.pop()!;
      if (visited.has(current)) {
        continue;
      }
      visited.add(current);
      const state = definition.states[current];
      for (const transition of state.transitions) {
        if (!visited.has(transition.target)) {
          queue.push(transition.target);
        }
      }
    }
    return visited;
  }

  it('all states are reachable from the initial state', () => {
    const reachable = collectReachableStates(TEST_WORKFLOW, TEST_WORKFLOW.initialState);
    for (const stateName of ALL_STATES) {
      expect(
        reachable.has(stateName),
        `State '${stateName}' is not reachable from '${TEST_WORKFLOW.initialState}'`,
      ).toBe(true);
    }
  });

  it('every non-terminal state can reach at least one terminal state', () => {
    for (const stateName of NON_TERMINAL_STATES) {
      const reachable = collectReachableStates(TEST_WORKFLOW, stateName);
      const reachesTerminal = TEST_WORKFLOW.terminalStates.some((t) => reachable.has(t));
      expect(reachesTerminal, `State '${stateName}' cannot reach any terminal state`).toBe(true);
    }
  });

  it('random walks through the graph always terminate within bounded steps', () => {
    fc.assert(
      fc.property(fc.array(fc.nat({ max: 20 }), { minLength: 0, maxLength: 200 }), (choices) => {
        let current = TEST_WORKFLOW.initialState;
        const visitCounts: Record<string, number> = {};

        for (const choice of choices) {
          if (TERMINAL_STATES.has(current)) {
            break;
          }

          visitCounts[current] = (visitCounts[current] ?? 0) + 1;

          const state = TEST_WORKFLOW.states[current];
          if (state.transitions.length === 0) {
            break;
          }

          const idx = choice % state.transitions.length;
          current = state.transitions[idx].target;
        }

        // Visit counts for any state should be bounded
        for (const [stateName, count] of Object.entries(visitCounts)) {
          expect(
            count,
            `State '${stateName}' visited ${String(count)} times — possible infinite loop`,
          ).toBeLessThanOrEqual(200);
        }
      }),
      { numRuns: 200 },
    );
  });
});
